{{- if .Values.kong.ingressController.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
plugin: acme
metadata:
  name: acme
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  account_email: dave.erichsen@gmail.com
  tos_accepted: true
  domains:
    - kic.erichsen.dev
  storage: redis
  storage_config:
    redis:
      auth: "{vault://env/REDIS_PASSWORD}"
      database: 0
      host: konnect-kic-dps-redis-master
      namespace: ""
      port: 6379
      ssl: false
      ssl_server_name: null
      ssl_verify: false
{{- end }}
