{{- if .Values.kong.ingressController.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
plugin: acme
metadata:
  name: acme
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  account_email: dave.erichsen@gmail.com
  domains:
    - kic.erichsen.dev
  api_uri: https://acme.zerossl.com/v2/DV90
  eab_hmac_key: "{vault://env/ZEROSSL_EAB_HMAC_KEY}"
  eab_kid: "{vault://env/ZEROSSL_EAB_KID}"
  storage: redis
  storage_config:
    redis:
      auth: "{vault://env/REDIS_PASSWORD}"
      database: 0
      host: konnect-kic-dps-redis-master
      namespace: ""
      port: null
      ssl: false
      ssl_server_name: null
      ssl_verify: false
{{- end }}
