apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cp-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: cp-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: /konnect/mesh-zone-cp-token
