apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-ssm
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: aws-ssm
            key: AWS_SECRET_ACCESS_KEY
