apiVersion: v2
name: konnect-kic
version: 2.17.0-rc.4
appVersion: 3.2.0
description: Kong gateway chart
sources:
  - https://github.com/kong/kong
type: application
dependencies:
  - name: kong
    version: 2.17.0-rc.4
    repository: https://charts.konghq.com
