apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  source:
    path: external-secrets/
    repoURL: 'https://github.com/erichsend/api.erichsen.dev'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    namespace: external-secrets
    name: in-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
