apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konnect-kic-dps
spec:
  project: default
  source:
    path: konnect-kong-proxies/
    repoURL: 'https://github.com/erichsend/api.erichsen.dev'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-kic-dps.yaml
  destination:
    namespace: konnect-kic
    name: in-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
