apiVersion: v2
name: konnect-kong-proxies
version: 2.39.0
appVersion: 3.7.0
description: Kong chart wrapper with dependencies
sources:
  - https://github.com/kong/kong
type: application
dependencies:
  - name: kong
    version: 2.39.0
    repository: https://charts.konghq.com
  - name: redis
    version: 17.7.5
    repository: https://charts.bitnami.com/bitnami
    condition: dependencies.redis.enabled
