dependencies:
  redis:
    enabled: true

kong:
  image:
    repository: kong/kong-gateway
    tag: "3.2"

  secretVolumes:
  - kong-cluster-cert

  admin:
    enabled: false

  proxy:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: api.erichsen.dev

  env:
    role: data_plane
    database: "off"
    cluster_mtls: pki
    cluster_control_plane: 79f296a65d.us.cp0.konghq.com:443
    cluster_server_name: 79f296a65d.us.cp0.konghq.com
    cluster_telemetry_endpoint: 79f296a65d.us.tp0.konghq.com:443
    cluster_telemetry_server_name: 79f296a65d.us.tp0.konghq.com
    cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
    cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
    lua_ssl_trusted_certificate: system
    konnect_mode: "on"
    vitals: "off"
  
  ingressController:
    enabled: false
    installCRDs: false
  
  replicaCount: 2

redis:
  architecture: standalone
  auth:
    passwordSecret: "redis-password"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
