requireClusterCert: false

dependencies:
  redis:
    enabled: false

kong:
  deployment:
    kong:
      enabled: false

  proxy:
    nameOverride: konnect-kic-dps-kong-proxy

  ingressController:
    enabled: true
    image:
      repository: kong/nightly-ingress-controller
      tag:  "2023-04-26"
      effectiveSemver: "v2.10.0"

    gatewayDiscovery:
      enabled: true
      adminApiService:
        name: konnect-kic-dps-kong-admin

    konnect:
      enabled: true
      tlsClientSecretName: konnect-client-tls
      runtimeGroupID: "a36c3b74-d858-46d9-9d66-34dcf9ea9c73"
      apiHostname: "us.kic.api.konghq.com"
