dependencies:
  redis:
    enabled: false

kong:
  deployment:
    kong:
      enabled: false

  proxy:
    nameOverride: konnect-kic-dps-kong-proxy

  ingressController:
    enabled: true
    image:
      repository: kong/kubernetes-ingress-controller
      tag:  "2.9.0-rc.1"
      effectiveSemver: "2.9.0"

    gatewayDiscovery:
      enabled: true
      adminApiService:
        name: konnect-kic-dps-kong-admin

    konnect:
      enabled: true
      tlsClientSecretName: konnect-client-tls
      runtimeGroupID: "3578a240-3f58-46cb-bce1-aa60715f344a"
      apiHostname: "us.kic.api.konghq.com"
